# Generated by Django 5.0.4 on 2024-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('PubMed', 'PubMed'), ('Dimensions', 'Dimensions'), ('Web of Science', 'Web of Science')], max_length=14),
        ),
    ]
