# Generated by Django 5.0.4 on 2024-04-20 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userprofile_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Scopus', 'Scopus'), ('PubMed', 'PubMed'), ('Dimensions', 'Dimensions'), ('Web of Science', 'Web of Science')], max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='choices',
            field=models.ManyToManyField(to='login.databasechoice'),
        ),
    ]
