# Generated by Django 5.0.4 on 2024-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_databasechoice_remove_userprofile_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='choices',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('PubMed', 'PubMed'), ('Dimensions', 'Dimensions'), ('Web of Science', 'Web of Science')], default='Scopus', max_length=14),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DataBaseChoice',
        ),
    ]
