# Generated by Django 5.0.4 on 2024-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_userprofile_choices_userprofile_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Scopus', 'Scopus'), ('PubMed', 'PubMed'), ('Dimensions', 'Dimensions'), ('Web of Science', 'Web of Science')], max_length=14, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='choice',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='databases',
            field=models.ManyToManyField(to='login.database'),
        ),
    ]
